### ISSUE TITLE
problems in murex_profile example

### ISSUE THREAD

**Issue by rapha8l** [lmorg/murex#267]
Hi,
Since last go get update, I get 

> Loading profile `.murex_preload`
> Loading profile `.murex_profile`
> exec: "func": executable file not found in $PATH
> exec: "func": executable file not found in $PATH
> exec: "func": executable file not found in $PATH
> exec: "func": executable file not found in $PATH
> exec: "func": executable file not found in $PATH
> exec: "func": executable file not found in $PATH
> 

It works afterwards if comment all func defined

By the way, is there any IRC chan ?

Thanks

**Comment by lmorg** [comment]
Hi

Yes, sorry for this. I generally try to avoid breaking changes but on this occasion I had deprecated `func` to standardise on using `function` like bash and others do. There's three fixes to this:
1.  I could "undeprecate" `func` -- however this isn't my preferred option. That said if yourself and others do actually like `func` then I'm happy to reverse my decision
2. You could add `alias func=function` to `.murex_preload` (which is one of the first scripts to load) and that would retain the backwards compatibility with `func`
3. Manually replace `func` with `function` in your `.murex_profile`

Personally, I'd favour the 3rd option the most but happy to discuss option 1 if that's genuinely used by other people.

As an aside, which `.murex_profile` are you using? Is it one you crafted yourself or one pulled from my gist? If the latter, that's a personal profile of mine so might go out of sync with this repository on occasions (basically if I forget to upload it) but I do try to keep it updated just in case anyone else (like yourself) did want to use it. The latest version (https://gist.github.com/lmorg/95622fd57f2091cdfe632c47d004cb23) does already have the `func`/`function` fix too. So might be worth pulling the latest gist if that's the profile you're working from. My long term plan here though, is to include all the good stuff from my gist into the main murex executable so you might see the contents of the gist get smaller as code is moved across.

> By the way, is there any IRC chan ?

Not at the moment. I do really like IRC as a platform but don't hang out on there much these days. But if you did want to some real time support I guess I could dig out my old Irssi config hehe

**Comment by lmorg** [comment]
Doh, just re-read your comment and realised you're talking about the `/example/murex_profile` -- sorry about that. I'd completely forgotten that file existed.

I'll get that fixed. And while I'm at it, I should probably include them in my unit testing.

**Comment by lmorg** [comment]
Fixed in ac1aa45 -- the latest copy on `master` should be working now. Change not (yet) merged into the develop branch but I expect that will be done tonight as well.

**Comment by lmorg** [comment]
@rapha8l I'm going to close this issue now as the fix has been merged into both `master` and `develop` branches. However I'm more than happy to re-open if your issue is persisting.

**Comment by rapha8l** [comment]
Thanks, sorry I was away for a long time

**Comment by lmorg** [comment]
@rapha8l That's absolutely fine 👍
