### ISSUE TITLE
A feature that should be more highlighted

### ISSUE THREAD

**Issue by bentxt** [lmorg/murex#283]
Hi,
Thanks for building murex and a preemptive sorry for misusing the issue system for this quick comment.

As a Fish Shell user for years I test out every promising new shell scripting language that (among other things) let me pipe lines to a block of code.

I'm very thrilled to see that murex supports it!
`
ls -> foreach i { out "yay " $i }`

Maybe you want to hightlight that more, since its such a great feature!
Good luck
Ben

**Comment by lmorg** [comment]
Hi @bentxt 

Thank you very much!

It doesn't just work with lines of a text file but also arrays within an object. For example lets create a JSON array with each day of the week
```
» ja [Monday..Sunday]
[
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
] 
```

and say we want to add a comment about whether it is a weekday or weekend:
```
if { $day->egrep "(Sat|Sun)" } then {
    out "$day is a weekend"
} else {
    out "$day is a weekday"
}
```

The whole one liner would look like this:

```
» ja [Monday..Sunday] -> foreach day { if { $day->egrep "(Sat|Sun)" } then { out "$day is a weekend" } else { out "$day is a weekday" } }
Monday is a weekday
Tuesday is a weekday
Wednesday is a weekday
Thursday is a weekday
Friday is a weekday
Saturday is a weekend
Sunday is a weekend
```

```
