### ISSUE TITLE
Crashes `murex` in "regex find"

### ISSUE THREAD

**Issue by judaew** [lmorg/murex#362]
#### Description

1. Install `murex` from [pre-compiled binaries](https://github.com/lmorg/murex/blob/master/INSTALL.md#pre-compiled-binaries-http-download) or source and execute its binary: 

```console
$ ./murex-darwin-amd64 
Loading profile `.murex_preload`
Loading profile `.murex_profile`

$ ~/Downloads »
```

2. Press Ctrl-r to search by "regex find":

```console
$ ~/Downloads »                                                                           
regex find:
```

3. Enter text (eg `/opt`...), then `mulex` crashes:

```console
panic: runtime error: invalid memory address or nil pointer dereference   
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1199369]                 

goroutine 1 [running]:
github.com/lmorg/murex/utils/readline.(*Instance).Readline(0xc000012b00, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/lmorg/murex/utils/readline/readline.go:147 +0xdc9
github.com/lmorg/murex/shell.ShowPrompt()
	/go/src/github.com/lmorg/murex/shell/shell.go:113 +0x19e
github.com/lmorg/murex/shell.Start()
	/go/src/github.com/lmorg/murex/shell/shell.go:64 +0x14c
main.startMurex()
	/go/src/github.com/lmorg/murex/main.go:149 +0x20a
main.main()
	/go/src/github.com/lmorg/murex/main.go:37 +0xcc
```

#### Tested on:

macOS 11.6 20G165 x86_64
Xcode 13.0 13A233
Go 1.17.1

**Comment by lmorg** [comment]
Thanks for the detailed bug report. Unfortunately I was unable to replicate your error, thankfully looking at the code I can see how the panic was raised and it's an easy fix too.

I'm pushing a patch shortly and the new binaries should be available to download in a couple of hours. Let me know if the bug persists :)

As an aside, I'm releasing a new version of _murex_ soon (v2.3, hopefully this weekend) which will include a number of other changes to the readline library in the hope to make CLI operations in the command line more discoverable.

**Comment by lmorg** [comment]
Merged into `master`. This update will be version `2.2.1300`

**Comment by judaew** [comment]
@lmorg Thanks, this fixed the problem.
