### ISSUE TITLE
Should murex: Deprecate `@[]` in favour of `range`?

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#476]
The `@[]` (https://murex.rocks/docs/commands/range.html) syntax sucks. It isn't memorable and is a nightmare for autocomplete to help. 

We should deprecate that in favour of a `range` builtin plus proper flags to affect behaviour.

**Comment by Pascalio** [comment]
Why couldn't ranges be selected with the `[ ]` syntax instead?
`a: [1..5] -> [ 2 4 ] 

3
5
a: [1..5] -> [ 2.. ]

3
4
5
`
And the flags of @[ could be useful for [ too, I guess...

**Comment by lmorg** [comment]
That's a really neat idea.
