### ISSUE TITLE
if and elif like control structure

### ISSUE THREAD

**Issue by Pascalio** [lmorg/murex#483]
Hi lmorg,

Restarted my murex journey!
I was surprised not to find any `elif`...
How do you recommend we should write something like
`if {$file -> f +F} {...}
elif {$file -> f +s} {...}
else {...}`

Best

**Comment by lmorg** [comment]
Hi, welcome back @Pascalio :)

That would be best served with a `switch` block:
https://murex.rocks/docs/commands/switch.html

To use your example

```
switch {
    case { $file -> f +f } {
        # ...
    }
    case { $file -> f +s } {
        # ...
    }
    catch {
        # ...
    }
}
```

You could condense this down to a one liner if you wanted but it would be ugly:
```
switch { case { $file -> f +f } { ... }; case { $file -> f +s } { ... }; catch { ... } }
```
(node the use of semi-colons `;` in the above)
