### ISSUE TITLE
Should murex: support a little syntactic sugar around cast?

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#484]
Take the following code
```
command parameters -> cast json -> [[ /path/to/obj ]]
```

the `cast` is explicit but extremely verbose. Maybe there’s an opportunity for some syntactic sugar. Eg
```
command parameters |&json| [[ /path/to/obj ]]
```

How do we implement something that’s fewer keystrokes for the interactive command line, while not looking completely alien.

**Comment by lmorg** [comment]
The problem with keywords is that shells allow barewords. Which would mean `as` would be ambiguous. The alternative would be forcing all strings to be quoted, which I think would be more painful than the _status quo_. This is the reason I was thinking about sandwiching the syntax around pipes, it makes it very explicit to the parser what is a command and parameters, and what is syntax sugar. 

`:type` might work though as it's uncommon. eg

```
command parameters -> :json [[ /path/to/obj ]]

curl -s https://api.github.com/repos/lmorg/murex/issues -> :json foreach issue { out "$issue[number]: $issue[title]" }
```

**Comment by Pascalio** [comment]
I see. Yes, an "as" keyword isn't so great, then.

`command -> :type command` looks very intuitive and easy to type to me. Perhaps slightly more so than 
`:type command -> command` -- Putting is before the pipe "feels" like we're somehow "parametrising" the first command, whereas after the pipe it feels more like something is going on along the pipe... What do you think?

**Comment by lmorg** [comment]
I completely agree. :)
