### ISSUE TITLE
Continue in for and foreach loops

### ISSUE THREAD

**Issue by Pascalio** [lmorg/murex#487]
**Describe the bug:**
I was trying to write something like:
```
-> foreach thing {
 command: $thing -> catch {
   out: "ouch"
   continue
 }
out: "yay"
....
....
}
```
But I can't find a "continue" mechanism... Knowing you, you've probably a good reason to have kept it out of the syntax, maybe because it's a keyword...
It is however practical to not have to use a full `if {success} {stuff} else {stuff}` syntax, leveraging the piped `catch` instead; especially if there's much after that catch, it helps keep the level of nested {} lower... 
What do you think?

**Comment by Pascalio** [comment]
Besides `catch` forwards the streams along the line, which if/else doesn't.

**Comment by Pascalio** [comment]
Grand, thank you!

**Comment by lmorg** [comment]
@Pascalio 

This should be sat in `develop` now and is due for release in version 3.0.x in the next week or so (or however long it takes to beta test this release)

**Comment by lmorg** [comment]
Doc: https://github.com/lmorg/murex/blob/develop/docs/commands/continue.md
