### ISSUE TITLE
Assignment syntax stores json as str

### ISSUE THREAD

**Issue by Pascalio** [lmorg/murex#508]
**Describe the bug:**
%{} and %[] do create json. But the syntax
`set var = ${} or $[]` casts that to string.
```
%{thing:{stuff:chow}}  -> debug -> [[ /Data-Type/Murex ]]
# json
set o = %{thing:{stuff:chow}}
$o -> debug -> [[ /Data-Type/Murex ]]
# str
%{thing:{stuff:chow}}  -> set o 
$o -> debug -> [[ /Data-Type/Murex ]]
# json

```

**Comment by lmorg** [comment]
`set` used as a function is largely just kept around for legacy support now after the expressions work we did at the end of last year. Eg

`foobar = %{foo: bar} `

The way `set` identifies the type is to be used either as a method (as in your example), or by passing an annotation, eg

`set json foobar = %{foo: bar}`

Unfortunately, altering the behaviour of `set` to treat the assignment as an expression is a no go is it would break backwards compatibility in unexpected ways.

**Comment by Pascalio** [comment]
Ahhh silly me! Had forgotten. Alright then ;)
