### ISSUE TITLE
create docs on job control

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#527]
eg `jobs`, `fid-list`, `bg`, etc

**Comment by orefalo** [comment]
I will take this one

**Comment by orefalo** [comment]
so, I started on this task.
I am learning at the same time.

Here is an unexpected user story

```
>> bg { sleep 10000000; echo done }
>> jobs
PID   State      Background  Process  Parameters
2334  Executing  true        exec     sleep 10000000
>> fg 2334
>> # I should not get a prompt, I should be on the sleep 1000...
```

am I missing something?

**Comment by lmorg** [comment]
That's definitely a bug. I'll take a look, albeit it probably wouldn't be in time for v5.0 release, which I'm hoping to do by the weekend.
