### ISSUE TITLE
How do I prevent murex from running “man -w” on thousands of man pages upon each invocation?

### ISSUE THREAD

**Issue by kseistrup** [lmorg/murex#530]
**Describe the query:**

It seems that on each interactive invocation `murex` is running `man -w` on each and every man page it can think of. This amounts to more than four thousand man pages on my ArchLinux box, and it takes `murex` several minutes to complete the task. The result doesn't seem to be cached anywhere. Even when murex is already running, a second interactive invocation will scan all the man pages again.

Q: How do I disable this behaviour?

**Expected behaviour:**

Ideally, `murex` ought to scan a man page when this is needed, but `murex` should at least cache the results and use the cached values.

**Additional context:**

I have looked for the issue in the guide, but didn't find anything.

I have looked for cached results in:

* `$XDG_DATA_HOME/murex/`  (non-existant)
* `$XDG_CACHE_HOME/murex/`  (non-existant)
* `$TMPDIR/murex*/`
* `$TMPDIR`

but couldn't find any caches.

I _can_ find `man -w` in `utils/man/man_unix.go`, but I am incompetent to find out how and where this is invoked.

**Documentation:**
Please rate your success with referring to the docs @ https://murex.rocks
- [ ] I haven't read the docs / the solution should be more discoverable
- [ ] I have read the docs but the content wasn't clear
- [x] I have read the docs but this query was missing
- [ ] I have read the docs and this query was answered but I'm still having problems

[add any additional detail, this will help us to write better docs]

* murex v3.1.3100
* ArchLinux x86_64

**Comment by lmorg** [comment]
Hi @kseistrup , thanks for your feedback.

You can disable the precache by putting the following line in your `~/.murex_profile`:
```
config set shell pre-cache-hint-summaries false
```
Feel free to browse through the other options in `config`, there's a lot of behaviour you can change.

> The result doesn't seem to be cached anywhere.

It is cached:
https://github.com/lmorg/murex/blob/master/utils/man/cache.go

Albeit the cache could take a while on slower machines.

> This amounts to more than four thousand man pages on my ArchLinux box, and it takes murex several minutes to complete the task.

It is a background thread so shouldn't lock up the shell. Are you seeing degraded performance while the pre-caching is performed? If so, I can look to get that addressed in the next release.

I run murex on a variety of Arch based systems (including a 10 year old i3 NUK with only 4GB RAM) but every system has an SSD of some description within it. So any feedback on performance would be gratefully received.

> Even when murex is already running, a second interactive invocation will scan all the man pages again.

The results are cached within a single murex session. However if you were to open another shell then that would be it's own murex session and would rerun the cache. murex doesn't run as a client server model so it cannot communicate data between sessions (this is something I've considered changing but haven't found strong enough arguments in favour of such a big redesign, plus there's arguments against such as breaking the ephemeral nature of shell sessions).

However if you have any thoughts on this then I'd welcome them.

**Comment by kseistrup** [comment]
> `config set shell pre-cache-hint-summaries false`

Thanks, that helped.

> It is cached:

I should, of course, have been explicit: cached _persistently_.

My `/usr/bin` directory currently holds 6,533 executables, and `/usr/share/man/man1` holds 4,265 man pages. Background process or not, I see it as completely overkill to trawl through all of these man pages for every interactive invocation of `murex` when in my daily work I use at most 100 of the thousands of commands available.

I haven't timed it, but I estimate it takes around 4 minutes to index the man pages, all the while the 1-minute loadavg lies around 1.25 (on a 4-CPU machine with spinning disks). While a loadavg of 1.25 is not alarming in any way, it's completely unnecessary and ought to be avoided [IMHO].

Personally, I would have chosen to cache the values and share a persistent cache among separate murex instances. The cache could either be updated _as necessary_ (i.e., when a man page not already in the cache is discovered), or maintained by e.g. a nightly cron job.

**Comment by lmorg** [comment]
I'm not a fan of a persistent cache because you then have an issue of knowing when to invalidate that cache (having invalid or out of date cache could be just as bad as not having any cache at all). And if you can work that much out that you might as well cache on demand rather than pre-cache. So I feel a persistent cache solves the wrong problem.

I can instead pivot the pre-cache to only scan executables shown in the active autocomplete window (that was the original plan to be fair, but I was running into issues with race conditions if the autocomplete option was changed quicker than the man page was parsed. So got lazy and did a full `$PATH` scan)

Disabling pre-cache also replicates that similar behaviour, except it only caches it once you've typed the full command name, thus you don't see the man page summary in autocomplete suggestions.

The method behind the madness of caching everything was to offer a little security for people newer to shells and not familiar with a lot of CLI tools. It allows them to navigate the library of commands on their computer with lower risk of running something bad by accident. But I do agree with your point that there is a sane middle ground that doesn't ram up your uptime averages.

**Comment by kseistrup** [comment]
> Disabling pre-cache also replicates that similar behaviour, except it only caches it once you've typed the full command name, thus you don't see the man page summary in autocomplete suggestions.

That's fine with me. The config setting you showed me has solved my problem.

Personally, I'd have have a persistent cache that if invalid at odd times than the current behaviour of repeatedly caching everything, even when caching a tenth or less is necessary.

A persistent cache is what utilities like `locate(1)`/`plocate(1)` is using. That works very well for me in upwards of 99% of cases. If I want to be sure, and I have a specific place to look, I'd use e.g. `find(1)` or `fd(1)`. I shudder to think about the experience if my shell decided to catalogue the entire disk at every invocation and didn't share the cache among instances.

But my immediate problem has been solved, and you know better than I do in which direction you want your software to go, so I think I'll end here by saying thanks for your help.

**Comment by lmorg** [comment]
Thanks for your input. I do appreciate your thoughts. This conversation has given me some ideas to try.

**Comment by kseistrup** [comment]
Great, thanks for the notification! :+1:
