### ISSUE TITLE
add alias: `builtin`

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#608]
**Describe the problem:**
Bash et al have a builtin literally called `builtin`

```
builtin [shell-builtin [args]]
```

Run a shell builtin, passing it args, and return its exit status. This is useful when defining a shell function with the same name as a shell builtin, retaining the functionality of the builtin within the function. The return status is non-zero if shell-builtin is not a shell builtin command.

(source: https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html)

**Possible ways to implement:**
Murex already has a builtin for managing such things: `fexec` (https://murex.rocks/docs/commands/fexec.html)

So we can just alias to that:

```
alias builtin=fexec builtin
```

**Additional context:**
This provides greater compatibility with POSIX / GNU shells

**Comment by orefalo** [comment]
Good addition.

on a similar thought, fish-shell has a 'command' literal, which allows to **bypass** all builtins and call a command executable.

This would turn out quite useful on OSX for instance, where the **open command** is not to be confused with the **open builtin**

Really like this shell btw

**Comment by lmorg** [comment]
Thanks for the feedback :)

Murex already has this but it's called `exec`: https://murex.rocks/docs/commands/exec.html (though that doc could use some TLC)

Regarding the `open` problem. I have a plan. The current `open` builtin basically duplicates macOS's `open` albeit it's more focused on a CLI experience (eg it will try to render images in the terminal where it can).
<img width="674" alt="image" src="https://github.com/lmorg/murex/assets/12153701/3277de99-8c65-4a8f-86b5-fd085856b890">
I can set the `open` builtin to fallback to the OS's default open handler (eg `open` on macOS, `open-xdg` on Linux) if there isn't any CLI handler for the Murex `open` builtin.

This way we can still have the all the functionality of the existing shell builtin but without breaking compatibility with the host OS (and there is always `exec open filename` for those edge cases).

**Comment by orefalo** [comment]
it will indeed be a welcome addition.
I am used to do -
'open <path>' -> to open Finder in the current folder

**Comment by lmorg** [comment]
Issue created for `open` #620

**Comment by lmorg** [comment]
Added `command` as an alias for `exec`

**Comment by orefalo** [comment]
thank you!

Question: if `exec` is `command`

what is the equivalent to the real `exec`?  which substitutes the current process with the application being called?

**Comment by lmorg** [comment]
sorry, i completely missed this message. There isn't an `exec` equivalent. I can't see me adding one either because any such code might require a lot of OS-specific code to maintain and would have limited usefulness (the only time I see bash's `exec` in the wild is in pseudo-aliases for `egrep` et al.

Plus since since Murex has it's own concept of function IDs under the hood, it's fair to describe Murex as an abstraction on top of OS primitives rather than exposing those primitives directly. So if process substitution is essential to someones code, then I suspect Murex would be the wrong tool for them regardless of whether process substitution was supported or not.

That's just my thoughts any ways. Not suggesting this is a closed matter
