### ISSUE TITLE
Ctrl+L - Clear and other shell "staples"

### ISSUE THREAD

**Issue by J-C-3** [lmorg/murex#611]
I might actually just be missing the proper configuration steps to do this, but I'm quite accustomed to normal shell navigation and hotkeys.

Is there a way to set some of those in the configuration or would I need to modify the readline library to set these bindings up?

First one I encountered is using `Ctrl+L` to clear, but there are others such as `Ctrl+A` to go to the beginning of the line or `Ctrl+U` to clear from the cursor to the beginning of the line... etc.

Nifty looking shell and excited to try it out more!

**Comment by lmorg** [comment]
`Ctrl+U` exists (albeit it clears the whole line but that's easy to change)

It would be trivial to add the others so I'll get them added in the next release.

For now, there are vim keybinding. Press `ESC` and you'll drop into VIM mode.

**Comment by J-C-3** [comment]
Thanks lmorg!

The vim keybindings are great, it's just that my brain doesn't switch from when I'm on a server vs local so adding some of that traditional shell shortcut goodness is very appreciated.

Thanks again for the awesome shell. I look forward to playing with it.

**Comment by xyproto** [comment]
`ctrl-l` is such a handy hotkey to quickly clear the screen. I don't believe the ViM mode provides this.

**Comment by distek** [comment]
Heyo! Not to throw a wrench in the PRocess, but will these be configurable? I'm thinking in the form of something like how inputrc currently works:
```
    "\C-A": beginning-of-line
    "\C-B": backward-char
    "\C-E": end-of-line
    "\C-F": forward-char
    "\C-K": kill-line
    "\C-L": clear-screen
```
Basically having predefined (and user defined? might be a bit much, though) functions that a user could then configure to be triggered by a key comb, with some sane defaults.

**Comment by J-C-3** [comment]
> Heyo! Not to throw a wrench in the PRocess, but will these be configurable? I'm thinking in the form of something like how inputrc currently works:
> 
> ```
>     "\C-A": beginning-of-line
>     "\C-B": backward-char
>     "\C-E": end-of-line
>     "\C-F": forward-char
>     "\C-K": kill-line
>     "\C-L": clear-screen
> ```
> 
> Basically having predefined (and user defined? might be a bit much, though) functions that a user could then configure to be triggered by a key comb, with some sane defaults.

I think that the event handler should `onKeyPress` should be able to do this conceptually. But, I had issues with interacting with my shell directly so I get the impression it’s a forked process and isn’t apart of my shell instance since I can send commands like `touch: foo` and the file is created but if I do `out: “bar”` I don’t get any output on stdout.

I didn’t open an issue for it yet as I hadn’t really looked into it further and I might be holding it all wrong.

https://murex.rocks/docs/commands/event.html

**Comment by lmorg** [comment]
@distek I could certainly do this, though it would mean those keys wouldn't be available for any other invocations of readline (eg via `read` builtin). The `onKeyPress` event was originally intended to be for the REPL shell and overrode any hotkeys in readline.

That's not to say that this behaviour couldn't be changed. It's just something for us to consider first

@J-C-3 `onKeyPress` expects stdout to be an object (eg JSON map). None of this is documented _anywhere_ though, so I can't blame you getting stuck on this. I don't think there's even support for writing to the terminal. I could probably do with rewriting the whole API as it's pretty horrible. Maybe pipe stdout to the terminal like people would expect but have special functions available via a named pipe?

**Comment by lmorg** [comment]
I think what I'll do for this release is have the hotkeys in their own functions so they can be redefined with `onKeyPress` but keep them hardcoded in `readline.go` as a default as well.

Conversations about whether they can be undefined, `read` command, etc can still happen but the above piece of work is worthwhile from a code cleanliness point of view regardless of any further decisions that might happen.

**Comment by distek** [comment]
Could there be a section of the config specially for the readline library? That way read could also take advantage of the key mappings (assuming `read`'s readline is just using the same code, I can't seem to find it at the moment). Then it could be implemented kinda like:

```go
func (rl *Instance) Readline() (_ string, err error) {
...
		if f, ok := ctrlCharMap[b[0]]; ok {
			f()
		} else {
			switch b[0] {
			case charTab:
				if rl.modeTabCompletion {
					rl.moveTabCompletionHighlight(1, 0)
				} else {
					rl.getTabCompletion()
				}
...
...

Where the `ctrlCharMap` is set in the config, keeping defaults if not assigned by the user

**Comment by distek** [comment]
Put aside all of what I'm going on about right now. If I have some time I'll cut a PR for this after 4.2's out if you're open to the idea.

**Comment by lmorg** [comment]
`read` uses the same readline code as the REPL. The problem is events are registered with the readline instance:
```

// Add a key to the event list
func (evt *keyPressEvents) Add(name, keySeq string, block []rune, fileRef *ref.File) error {
	if shell.Prompt == nil {
		return errors.New("unable to register event with readline API")
	}

	shell.Prompt.AddEvent(keySeq, evt.callback)
	evt.events = append(evt.events, keyPressEvent{
		name:    name,
		keySeq:  keySeq,
		block:   block,
		fileRef: fileRef,
	})
	return nil
}
```
https://github.com/lmorg/murex/blob/master/builtins/events/onKeyPress/keypress.go#L55

That all said, all that is registered is a callback function and the function parameters are stored in a slice in `onKeyPress` package. So it's possible I could push those events to other instantiations of readline too. I could even add a property to `onKeyPress` (or better yet(?), another event like onReplKeyPress) for events that people don't want defined globally for readline.

The other problem this throws up is whether there should be an expectation that any shell scripts honour these events too. By default, user profiles are not loaded if a script is executed (basically the same as interactive vs non-interactive usage of Bash et al). Which would mean if we want any readline defaults persistent then they might have to live in their own config file.

> Put aside all of what I'm going on about right now. If I have some time I'll cut a PR for this after 4.2's out if you're open to the idea.

I'm very open to contributions. Regardless of how big or small. Even just correcting typos in documents. But if anyone is open to contributing code as well, well then I'd be honoured to accept your time and code :)
