### ISSUE TITLE
CTRL+K Clear the line from cursor

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#613]
**Describe the problem:**
Hi,

Just pointing a handy shortcut in other shells
CTRL+A gets to the beginning of the line
CTRL+E gets to the end of the line
CTRL+K Clears the line from cursor

Thank you

**Comment by orefalo** [comment]
this is an extended list

https://gist.github.com/2KAbhishek/9c6d607e160b0439a186d4fbd1bd81df

**Comment by lmorg** [comment]
Oh that's super helpful. Thank you!

**Comment by lmorg** [comment]
I'm going to close this as part of the next release. Updates can remain on #611 as that has a deeper conversation going

**Comment by lmorg** [comment]
merged to `master`
