### ISSUE TITLE
Escape codes messed up console on windows 

### ISSUE THREAD

**Issue by CompuRoot** [lmorg/murex#614]
## Describe the bug:
Run Windows command line console `cmd` or `powershell`. Run `murex`, upon start `murex` using color escape codes that doesn't processed by neither windows `cmd` nor `powershell`     
Adding `config: set shell color false` into `C:\Users\SomeUser\.murex_profile` is ignored.

Start up screen is looks like that:
```
]2;alias]2;function]2;function]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;private]2;autocomplete]2;autocomplete]2;private]2;private]2;private]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;private]2;private]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;private]2;autocomplete]2;private]2;autocomplete]2;private]2;private]2;autocomplete]2;private]2;autocomplete]2;autocomplete]2;private]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;alias]2;private]2;autocomplete]2;private]2;autocomplete]2;config]2;alter]2;!if]2;man-summary]2;summary]2;autocomplete]2;autocomplete]2;!if]2;man-summary]2;summary]2;!if]2;man-summary]2;summary]2;!if]2;man-summary]2;summary]2;function]2;summary]2;autocomplete]2;config]2;openagent]2;if]2;which]2;if]2;which]2;if]2;which]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;alias]2;autocomplete]2;alias]2;method]2;config]2;alter]2;alias]2;alias]2;alias]2;alias]2;alias]2;alias]2;alias]2;alias]2;alias]2;alias]2;alias]2;autocomplete]2;autocomplete]2;private]2;autocomplete]2;autocomplete]2;private]2;autocomplete]2;private]2;autocomplete]2;autocomplete]2;autocomplete]2;alias]2;method]2;config]2;append]2;private]2;autocomplete]2;autocomplete]2;autocomplete]2;autocomplete]2;private]2;autocomplete]2;autocomplete]2;config]2;append]2;autocompleteLoading profile `.murex_preload`
Loading profile `.murex_profile`
]2;config[31mInvalid titlebar-func. Block returned false.
[0m]2;murex
```
BTW, there also is error: `Invalid titlebar-func`

The only way to make murex useful in console is to issue some nonexistent command like `abcdsertyrty` and after pressing enter it will behaves like on `Linux`, as it supposed to

## Expected behavior:
Respect profile settings that direct to avoid to use escape color codes

## Platform (please complete the following information):
 - OS: Windows standard 2019 x64 (Also tried on Win10,8,7) 
 - Terminal Emulator: `cmd` & `powershell`
 - Murex version: murex v4.1.7300

**Comment by lmorg** [comment]
@CompuRoot just pushing a patch to the `develop` branch.

**Comment by lmorg** [comment]
While this is fixed, I had noticed some other escape codes weren't being picked up correctly (namely cursor movement). I'm pretty sure this used to work but I'll close this issue and create a new one for that
