### ISSUE TITLE
Rosetta stone: `N/A` statement regarding `bash` has no multiline comments

### ISSUE THREAD

**Issue by CompuRoot** [lmorg/murex#616]
## Describe the bug (I think it would be more correction than a bug of documentation):

[Rosetta Stone](https://murex.rocks/docs/user-guide/rosetta-stone.html) on web site states
|Description|bash|murex|
|-----------------|  ---   |  ---     |
|Multiple lines| 	n/a 	|/#<br>line 1<br>line 2<br>#/|

## Expected behavior:
|Description|bash|murex|
|-----------------|  ---   |  ---     |
|Multiple lines| 	:<<EOC<br>comment 1<br>comment 2<br>EOC 	|/#<br>line 1<br>line 2<br>#/|

**Comment by lmorg** [comment]
Thanks for the correction there. I've stages to update to get pushed to the website with the next release

**Comment by lmorg** [comment]
merged to `master`
