### ISSUE TITLE
Automatic directory change without explicit `cd`/`chdir` command (auto_cd)

### ISSUE THREAD

**Issue by gcv** [lmorg/murex#618]
**Describe the problem:**

Murex would benefit from a zsh-style autocd feature, where just typing the name of a directory would switch to it. In zsh, that's enabled with `setopt auto_cd` and in Bash with `shopt -s autocd`.

I have not found this in the documentation.

**Possible ways to implement:**

n/a

**Additional context:**

n/a

**Documentation:**

Please rate your success with referring to the docs @ https://murex.rocks
- [ ] I haven't read the docs / the solution should be more discoverable
- [ ] I have read the docs but the content wasn't clear
- [X] I have read the docs but this query was missing
- [ ] I have read the docs and this query was answered but I'm still having problems

**Comment by lmorg** [comment]
@gcv Thanks for the suggestion.

I'll get this added to the next release

**Comment by lmorg** [comment]
@gcv this has been added. It is disabled by default. You can enable it via
```
config set shell auto-cd true
```

**Comment by gcv** [comment]
Thank you, that looks great!

**Comment by lmorg** [comment]
@gcv I haven't added any autocompletions yet. So you cannot type (for example) `~/Dow` and have `~/Downloads` suggested. Shouldn't be hard to get that added though

**Comment by lmorg** [comment]
merged to `master`
