### ISSUE TITLE
[Meta?] Enable Github Discussions for Murex

### ISSUE THREAD

**Issue by distek** [lmorg/murex#621]
**Describe the problem:**
From what I've noticed across various repos/orgs, Github discussions is helpful in mitigating "Issues" overload by having simpler questions answered that aren't actually bug reports/feature requests. As an added bonus, the community will rather answer the question, or, help in determining if it _is_ actually a bug the user is experiencing and maybe give tips on how to properly report it.

Can also be a place for the community to show off their sweet configs and what not. :)

**Possible ways to implement:**
I believe it's a checkbox in settings. Afterwards, maybe sticky an issue stating "general questions should be directed to Discussions" or something to that effect.

**Additional context:**
https://github.com/koekeishiya/yabai/discussions

**Documentation:**
Add mention of Discussions for general questions to the docs as well, should you choose to go down this route.

**Comment by lmorg** [comment]
Good idea. I'd been wanting to set up something like this. Was leaning towards IRC but this is much more convenient.

https://github.com/lmorg/murex/discussions

**Comment by distek** [comment]
Thanks! I'll close this.
