### ISSUE TITLE
Add Ctrl-g as Esc equivalent

### ISSUE THREAD

**Issue by gcv** [lmorg/murex#623]
**Describe the problem:**

Those of us with Emacs muscle memory tend to hit Ctrl-g to get out of things. Would it be possible for Murex to do the same thing? It should get out of Ctrl-f and Ctrl-r modes, for example. It would be a great complement to the recent additions of Ctrl-a and Ctrl-e.

**Possible ways to implement:**

n/a

**Additional context:**

**Documentation:**
Please rate your success with referring to the docs @ https://murex.rocks
- [ ] I haven't read the docs / the solution should be more discoverable
- [ ] I have read the docs but the content wasn't clear
- [X] I have read the docs but this query was missing
- [ ] I have read the docs and this query was answered but I'm still having problems

**Comment by lmorg** [comment]
merged to `master`
