### ISSUE TITLE
Command history with arrow keys on Windows

### ISSUE THREAD

**Issue by kmatt** [lmorg/murex#630]
### Discussed in https://github.com/lmorg/murex/discussions/629

murex v4.2.5110

<div type='discussions-op-text'>

<sup>Originally posted by **kmatt** June 22, 2023</sup>
Compared to Murex on macOS, up arrow on Win10 does not retrieve command history, in either Windows Terminal or Alacritty.

Is this configurable, or an issue with the readline implementation?</div>

**Comment by kmatt** [comment]
Left and right arrows also don't select auto-complete options, only the left most selection is available:

```
murex » vim ~/.mur

 ~/.murex_history   ~/.murex_modules/  ~/.murex_preload   ~/.murex_profile
```

**Comment by lmorg** [comment]
You can use `tab` to move selections too, but you're right that the arrow keys should work here as well.

This behaviour isn't (yet) configurable but it should just work out of the box. I'll take a look this weekend.

**Comment by lmorg** [comment]
This is proving more difficult than I hoped. For reasons I haven't yet figured out, Windows Terminal isn't sending any escape codes when the arrow keys are pressed.

I'm assuming it is because I'm not setting the terminal mode correctly. But I've not gotten much further in my investigation thus far

**Comment by kmatt** [comment]
Note I'm seeing the same issue with both Windows Terminal and Alacritty 0.9.0 on Windows, so this may be a Windows thing.

**Comment by lmorg** [comment]
It's definitely a Windows thing. The problem is Windows doesn't have TTYs like Linux/UNIX. In fairness, TTYs themselves introduce so many issues so I'm not trying to suggest TTYs are better. But the problem here is I need to write some radically different code to compensate for the different console backend.

I've been having a read through some other code out there, like termbox, and it's given me some ideas.

**Comment by kmatt** [comment]
Borrowing from  https://github.com/containerd/console/blob/65eb8c0396d0cac15c888bcf4d47049c21317b18/console_windows.go#L191

Seems to enable arrow keys history in a build of 4.3. I did not make a PR because I don't know if this is sufficient.

```
Δ utils/readline/raw_windows.go
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

─────────────────────────────────────────────┐
• 41: func MakeRaw(fd int) (*State, error) { │
─────────────────────────────────────────────┘
        return nil, err
    }
    raw := st &^ (windows.ENABLE_ECHO_INPUT | windows.ENABLE_PROCESSED_INPUT | windows.ENABLE_LINE_INPUT | windows.ENABLE_PROCESSED_OUTPUT)

    raw |= windows.ENABLE_VIRTUAL_TERMINAL_INPUT

    if err := windows.SetConsoleMode(windows.Handle(fd), raw); err != nil {
        return nil, err
    }

```

**Comment by lmorg** [comment]
Awesome, thank you. I’ll give that a try. 

Can I ask a favour, do you mind writing up some instructions on how to install the additional tooling to compile from source on Windows? At the moment I’m just cross compiling from Linux myself so it would help with my own testing let alone others coming to Murex from Windows.

**Comment by kmatt** [comment]
@lmorg thankfully it was only ensuring that a gcc was in the path: 

https://github.com/kmatt/murex/blob/v4.3/INSTALL-Windows.md

**Comment by lmorg** [comment]
How about the other coreutils stuff? Was that just MinGW?

**Comment by kmatt** [comment]
I don't have MinGW installed, only coreutils are from Git for Windows and BusyBox. Its likely the Git usr path was used because its the first in my path:

```
> which ls
C:\Program Files\Git\usr\bin\ls.exe
```

**Comment by kmatt** [comment]
Probably all from Git for Windows, as I don't have a MinGW installed directly:

* C:\Program Files\Git\mingw64\bin
* C:\Program Files\Git\usr\bin

Since AFAIK there is not an equivalent to Python's virtualenv for Go, I'm spinning up a clean Windows 11 VM to see what would be needed when not having existing development tools in place.

After the 21.5 _GB_ image downloads ...

**Comment by kmatt** [comment]
Its now building on a Win11 VM _without_ Git or MinGW or a GCC being installed. I was certain a gcc was required for `go-sqlite3` previously.

Would building on Windows without any dependencies installed other than Go be expected?

**Comment by lmorg** [comment]
honestly, I was sure gcc was required for sqlite3 too. Also you'd need `git` to import dependencies as part of the `go build` (go modules use `git` under the hood).

Is it possible that Win11 image has git and gcc already installed?

**Comment by lmorg** [comment]
> Borrowing from https://github.com/containerd/console/blob/65eb8c0396d0cac15c888bcf4d47049c21317b18/console_windows.go#L191
> 
> [kmatt@98aef42](https://github.com/kmatt/murex/commit/98aef426d94c0fc68df48bce2f486fe6d0afabef)
> 
> Seems to enable arrow keys history in a build of 4.3. I did not make a PR because I don't know if this is sufficient.
> 
> ```
> diff --git a/utils/readline/raw_windows.go b/utils/readline/raw_windows.go
> index e2ee386b..188f55e9 100644
> --- a/utils/readline/raw_windows.go
> +++ b/utils/readline/raw_windows.go
> @@ -41,6 +41,9 @@ func MakeRaw(fd int) (*State, error) {
>                 return nil, err
>         }
>         raw := st &^ (windows.ENABLE_ECHO_INPUT | windows.ENABLE_PROCESSED_INPUT | windows.ENABLE_LINE_INPUT | windows.ENABLE_PROCESSED_OUTPUT)
> +
> +       raw |= windows.ENABLE_VIRTUAL_TERMINAL_INPUT
> +
>         if err := windows.SetConsoleMode(windows.Handle(fd), raw); err != nil {
>                 return nil, err
>         }
> ```

That did exactly the job! Thank you
