### ISSUE TITLE
Feature Request -- Word Jumping with Ctrl+Arrow Keys

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#644]
**Describe the problem:**
I switched to murex a couple of weeks ago and have really been enjoying it! However, one thing I miss from bash and fish is the ability to jump to the previous and next words in the current line using Ctrl+Left Arrow Key and Ctrl+Right Arrow Key, respectively. I'm aware I can achieve something similar by pressing Esc and using the Vim keys, but to me the using the Ctrl and arrow keys is much quicker and more intuitive.

**Possible ways to implement:**
When not in Vim mode, Ctrl+Left Arrow Key would behave like _b_ does in Vim mode, and Ctrl+Right Arrow Key like _e_ does.

**Additional context:**
Also, while reading the documentation relating to the terminal hotkeys [here](https://murex.rocks/docs/user-guide/terminal-keys.html) I noticed a minor issue, the title of that page seems to be {{WEBSITE_PAGE_TITLE}}

**Documentation:**
Please rate your success with referring to the docs @ https://murex.rocks
- [ ] I haven't read the docs / the solution should be more discoverable
- [ ] I have read the docs but the content wasn't clear
- [x] I have read the docs but this query was missing
- [ ] I have read the docs and this query was answered but I'm still having problems

**Comment by lmorg** [comment]
@tiymat Thank you for the feedback.

There are other hotkeys for jumping words which admittedly haven't made their way into the docs yet: https://murex.rocks/docs/changelog/v4.2.html

However I've just pushed an update to `develop` branch that should also add the ctrl+(left|right) arrow keys too. I'm hoping to merge that branch into main later this week.

---

Good spot re the page title. I'll take a look at that as well

**Comment by tiymat** [comment]
That's great -- I'll look out for that update. Thanks!

**Comment by lmorg** [comment]
merged into 4.4 release
