### ISSUE TITLE
type inference issue

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#674]
**Describe the bug:**

```
murex-utils » a=33
murex-utils » echo $a
33
murex-utils » round ${$a * $a} 1
Error in `expr` (0,2): cannot Multiply non-numeric data types
                     > Expression: $a * $a
                     >           :    ^
                     > Character : 4
                     > Symbol    : Multiply
                     > Value     : ''
```

**Expected behaviour:**
It looks like a=33 is infered to be a string,  
I would expect 1089 as an output

**Comment by lmorg** [comment]
Coincidentally this is down the the double parsing we chatted about earlier. The expression pre-parser doesn't expand variables (for speed) but I'd forgotten to add a check that variables are valid values.

Fix pushed to dev

**Comment by lmorg** [comment]
(I’m actually a little annoyed at myself for not having this covered in a test)

**Comment by orefalo** [comment]
fixed, ty
