### ISSUE TITLE
Struggling with round

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#675]
**Describe the bug:**

I am struggling with round....
what am I doing wrong?

```
murex-utils » pfree=855578
murex-utils » pfre = round ${$pfree * 4096} 0.99
expecting an operation
Expression: pfre = round ${$pfree * 4096} 0.99
          :             ^
Character : 13
Symbol    : Calculated
Value     : '${$pfree * 4096}'
```

**Expected behavior:**
proper round calculation

**Comment by lmorg** [comment]
This is due to expressions and statements not being equal. If you want it as an expression then you'll need to subshell it:

```
pfre = ${round ${$pfree * 4096} 0.99}
```

if you want to write this as a statement then it should look like:

```
round ${$pfree * 4096} 0.99 -> set pfre
```

**Comment by orefalo** [comment]
This is really not intuitive...  
but fine - closing.

Ideally, murex should be able to accept either
```
pfre = round ($pfree * 4096) 0.99
round ($pfree * 4096) 0.99 -> set pfre
```
