### ISSUE TITLE
Inconsistent curly brace behaviour in strings

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#697]
**Describe the bug:**
```
curl -so /dev/null -w '%{response_code}\n%{time_total}' https://example.com
```
runs as expected. But
```
function foo { curl -so /dev/null -w '%{response_code}\n%{time_total}' https://example.com }
```
causes an error, seemingly indicating the `}` after `response_code` as the culprit.

My reading of [the documentation](https://dev.murex.rocks/parser/string.html#detail) is that `%{ }` constructs within single quotes will not be expanded.

I think it has something to do with the presence of the curly braces enclosing the code block, as it works without them, and
```
%[1] -> foreach var { curl -so /dev/null -w '%{response_code}\n%{time_total}' https://example.com }
```
also errors in the same way.

**Expected behaviour:**
The curl command with the curly braces in its `-w` argument should behave consistently whether or not it's in a `{ }`-demarcated code-block, or the documentation should be updated to be more explicit about whether/how `{` characters should be escaped within code blocks.

**Screenshots:**
N/A

**Platform (please complete the following information):**
 - OS, output from `uname -a` if supported: Linux tiymat-desktop 6.2.0-27-generic # 28-Ubuntu SMP PREEMPT_DYNAMIC Wed Jul 12 22:39:51 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Terminal Emulator: GNOME Terminal
 - Murex version, output from `version --no-app-name`: 4.4.9500

**Additional context**
N/A

**Comment by lmorg** [comment]
Nice find!!

I started typing out a comment explaining how the behaviour was correct before I grokked what discovered. So I'm impressed you managed to debug this.

I'm just pushing a fix to `develop` now (assuming all tests pass):
<img width="867" alt="image" src="https://github.com/lmorg/murex/assets/12153701/324aea60-d6f1-49ca-908e-2922a6de7393">

**Comment by tiymat** [comment]
Wow, can't say I expected a fix so soon! Thanks!

**Comment by joshahussey** [comment]
Commendable.
