### ISSUE TITLE
Addition key shortcuts

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#701]
**Describe the problem:**
Low priority, yet it will please all these console lovers  ;-)

| Shortcut            | Description                           |
| ---                 | ---                                   |
| `CTRL+←`/`CTRL+→`       | Move to the line beginning/end, similar to CTRL+A and CTRL+E        |
| `↑`/`↓`             | Switch to the previous/next command in history, it's actually a search which uses the input from the line to search/present history matches  |

PS: Murex is now my main shell, love it

**Comment by lmorg** [comment]
> Move to the line beginning/end, similar to CTRL+A and CTRL+E

`Alt` (`option` on macs) + `←` and `→` also do this. I can definitely add `ctrl` as well though.

> `↑`/`↓`

If I understand correctly, so you mean if the command line is empty, then the next/previous in history. If the command line is not empty, then the next/previous that matches the partial command line?

If so, what's the intended behaviour if there are no matches?

> PS: Murex is now my main shell, love it

Excellent. And thank you for the kind words

**Comment by orefalo** [comment]
> Alt (option on macs) + ← and → 

Moves the back/forth to the previous word in the line (at least in my iterm)
it's a different functionality


> If I understand correctly, so you mean if the command line is empty, then the next/previous in history. If the command line is not empty, then the next/previous that matches the partial command line?

correct. if no match it won't propose anything

ie.
```
>> history
ls
ls -l
out country
ls -lR
out ls -l
>> ls -l
# up/down on the above line will toggle between ls -l, ls -lR and out ls -l
>> printf
# up/down no match - printf stays in place
``

**Comment by lmorg** [comment]
I forgot to label this issue number in the commit message, but I've pushed a fix for up and down.

ctrl+left and right will have to wait until I'm back on Linux because macOS maps ctrl+left/right to window manager operations (which is why I originally binded jump word to `command` instead of `ctrl`).

**Comment by orefalo** [comment]
ty

**Comment by orefalo** [comment]
Closing -

Turns out CTRL+←/CTRL+→ may be opinionated.
`fish` has it, `bash` and `zsh` don't.

Considering that on OSX the shortcut is used by the window manager (good point) - better hold off.
