### ISSUE TITLE
Homebrew install location differs on Intel

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#706]
**Describe the bug:**
murex-module's dependency validation can't find executables, 
I can confirm they are in PATH
Looks like Murex does not re-read the ENV variables post `.murex_preload` evaluation

**Expected behaviour:**

**Screenshots:**

```
Loading profile `.murex_preload`
Before /usr/bin:/bin:/usr/sbin:/sbin
After /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Loading module `murex-module-free/free`
Loading module `murex-module-homeendkey/home-end-keys`
Loading module `murex-module-javahome/javahome`
Loading module `murex-module-orefalo/profile`
Loading module `murex-module-orefalo/sublime-link`
Loading module `murex-module-orefalo/k9s`
Loading module `murex-module-orefalo/starship-config`
Loading module `murex-module-orefalo/local-docker`
There were problems loading modules `/Users/orefalo/.murex_modules/`:
Error loading module `jump` in path `/Users/orefalo/.murex_modules/jump/jump.mx`:
  * Missing required executable, builtin or murex function: `jump`
Error loading module `docker-compose` in path `/Users/orefalo/.murex_modules/murex-module-dockercompose/docker-compose.mx`:
  * Missing required executable, builtin or murex function: `docker-compose`
Error loading module `grc` in path `/Users/orefalo/.murex_modules/murex-module-grc/grc.mx`:
  * Missing required executable, builtin or murex function: `grc`
Error loading module `starship` in path `/Users/orefalo/.murex_modules/murex-module-starship/starship.mx`:
  * Missing required executable, builtin or murex function: `starship`
Loading profile `.murex_profile`
```

**Additional context**

So this is a weird issue, which seems to be platform dependent.
I won't call it a bug, b/c I can't confirm the issue is murex.

I have two mac on the same OS version. one is Arm M1, the other Intel.
the major difference between the two is that brew installs in different folders
... and also configures the default path differently - I just figured out the source of the issue ;-)

But here is the core of the issue...
While debugging, I created this script

```
>> cat .murex_preload
# This file is loaded before any murex modules. It should only contain
# environmental variables required for the modules to work eg:
#
#     export PATH=...
#
# Any other profile config belongs in your profile script instead:
# /Users/orefalo/.murex_profile

out Before $PATH
$PATH -> :paths: prepend /usr/local/bin -> export PATH
out After $PATH
```

turns out, it didn't solve the issue. like if murex didn't read the new environment variable.

**Comment by lmorg** [comment]
This is likely an issue with homebrew where it stores things in weird locations and then updates $PATH itself. I bet if you launch murex from zsh then it will work (because murex would inherit $PATH from zsh)

I've got a workaround  https://github.com/lmorg/murex/blob/master/config/defaults/profile_preload.mx but if you're experiencing this issue then it's likely one of those conditions isn't being met.

If you take a look at the above script and see what's failing, I can apply that fix to Murex.

**Comment by orefalo** [comment]
Right, I can confirm an environment issue with brew, that's fine.

What I am pointing at, is that when `.murex_preload` is evaluated, if it changes a env variable, the rest of the scripts are not picking it up.

**Comment by lmorg** [comment]
They definitely are. This is exactly why `.murex_preload` was created and is how I have all my machines set up.

* What happens when you run `$PATH` from the terminal (ie after `.murex_preload` has run)?
* Also from zsh, run `which jump`

**Comment by orefalo** [comment]
Laurence,

You have a M1 Mac, murex works also perfectly for my on this machine - 

But on Intel Mac,  brew installs its executables under /usr/local/bin - which for some reason is not set by default.

By now, I have confirmed that
1. /usr/local/bin/starship is there
2. I have added /usr/local/bin in the PATH using the `.murex_preload` script
3. I can even confirm, you are right, that the PATH is properly exported. I change the jump module, and did an `out $PATH`. It is set

Now, for some weird reasons, this validation fails

```
	for _, cmd := range m.Dependencies.Required {
		if !(*autocomplete.GlobalExes.Get())[cmd] && lang.GoFunctions[cmd] == nil && !lang.MxFunctions.Exists(cmd) {
			message += "  * Missing required executable, builtin or murex function: `" + cmd + "`" + utils.NewLineString
		}
	}
```

- Are you caching the exe internally?

**Comment by orefalo** [comment]
I still believe you have a bug.. but I am making progress

I now understand why it works on M1 and not Intel.
For some obscure reason, I have this file on M1 and not on Intel...

```
# ~/.profile
eval "$(/opt/homebrew/bin/brew shellenv)"
```

when running the command you get
```
➜  /opt/homebrew/bin/brew shellenv
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
```

**Comment by lmorg** [comment]
that'll be your problem. You can see homebrew is updating your `$PATH` and that path isn't being set by your murex profiles. So it's not that the profiles aren't retaining $PATH env correctly, it's that they don't include every required path.

Murex should detect homebrew and run that `shellenv` function automatically though. Can you run the following:
```
if { os darwin && g /opt/homebrew/bin/brew } then {
    out "woopwoop"
}
```

**Comment by orefalo** [comment]
I had to change the PATH

```
if { os darwin && g /usr/local/bin/brew } then {
    out "woopwoop"
}
woopwoop
```

At this point, I believe it's an OSX security feature.
there is a good reason brew went from `/usr/local/bin` to `/opt/homebrew/bin`

anyways.. think I will just remove the dependencies to let it pass on this platform.

**Comment by lmorg** [comment]
leave the dependencies in. I'll just update the above code to check in both /opt and /usr/local

**Comment by orefalo** [comment]
https://www.reddit.com/r/MacOS/comments/jw9guu/why_did_homebrew_move_from_usrlocalto_opthomebrew/

**Comment by lmorg** [comment]
Right, try now. The homebrew compatibility layer is this:
```
if { os darwin && %[ /usr/local/bin/brew ] -> f +x } then {
    /bin/zsh -c 'eval "$(/usr/local/bin/brew shellenv)"; env' \
    -> grep -Ei "(HOMEBREW|PATH)" \
    -> prefix "export " \
    -> source
}

if { os darwin && %[ /opt/homebrew/bin/brew ] -> f +x } then {
    /bin/zsh -c 'eval "$(/opt/homebrew/bin/brew shellenv)"; env' \
    -> grep -Ei "(HOMEBREW|PATH)" \
    -> prefix "export " \
    -> source
}
```

**Comment by orefalo** [comment]
it works!
thanks for the quick fix.


it's not old versions of osx, I am on the latest venture 13.5.1, as per the link above - brew executables are not universal. For this reason they picked a different folder for the two different architectures - intel and arm

**Comment by lmorg** [comment]
ahhhh

**Comment by orefalo** [comment]
I am reopening this ticket.
I may have found a way around `zsh`

```
 brew shellenv -> sed 's/${PATH+:$PATH}/:$PATH/' -> \
 sed 's/${MANPATH+:$MANPATH}:/:$MANPATH/' -> \
 sed 's/${INFOPATH:-}/$INFOPATH/' -> source
```

PS1: can't believe it was so simple 
PS2: the following code doesn't work with `regexp`, can't explain why


```
 brew shellenv -> regexp 's/${PATH+:$PATH}/:$PATH/' -> \
 regexp 's/${MANPATH+:$MANPATH}:/:$MANPATH/' -> \
 regexp 's/${INFOPATH:-}/$INFOPATH/' -> source
```

**Comment by lmorg** [comment]
> I am reopening this ticket. I may have found a way around `zsh`
> 
> ```
>  brew shellenv -> sed 's/${PATH+:$PATH}/:$PATH/' -> \
>  sed 's/${MANPATH+:$MANPATH}:/:$MANPATH/' -> \
>  sed 's/${INFOPATH:-}/$INFOPATH/' -> source
> ```
> 
> PS1: can't believe it was so simple PS2: the following code doesn't work with `regexp`, can't explain why
> 
> ```
>  brew shellenv -> regexp 's/${PATH+:$PATH}/:$PATH/' -> \
>  regexp 's/${MANPATH+:$MANPATH}:/:$MANPATH/' -> \
>  regexp 's/${INFOPATH:-}/$INFOPATH/' -> source
> ```

possibly because `$`, `+` and `{}` tokens have special meanings in regex:
- `$`: denotes end of line
- `+`: matching one or more of the preview match
- `{...}`: denote repetition of the previous match

eg
- `(bar){3}$` would match: `foobarbarbar` but not `foobar`.
- `(bar)+$` would match: both `foobarbarbar` and also `foobar`


So if you want `$`, `+` and `{}` to be matched as characters rather than tokens, you need to escape them, eg `'\$\{MANPATH\+:\$MANPATH\}:`

As for why it worked in `sed`, I don't know about that. It's a different regex engine so it might be more lenient with malformed regex expressions. eg having `$` at the start of the line and `{...}` that contain non-numeric characters. This might also be a behaviour that isn't portable (GNU sed does behave differently to BSD sed in a number of ways).
