### ISSUE TITLE
logical operators should behave differently in expressions vs statements

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#708]
**Describe the bug:**
`command && command` works like Bash et al. However what should the expected behaviour be with
```
foo = (bar() && baz())
# ...or...
for = ($bar && $bar)
```

**Expected behaviour:**
That is what this issue is expected to decide upon

**Comment by orefalo** [comment]
indeed,

the first is a conditional evaluation
the other is a boolean expression

**Comment by lmorg** [comment]
This should actually be pretty easy for the parser to manage because we could say any && or || inside parentheses (which we are already considering as an expression) is treated as a boolean operator instead of a conditional.

It could make the context of && and || a little confusing though since we are now overloading those particular tokens. 

What’s your thought?

**Comment by lmorg** [comment]
actually, there's no reason `&&` cannot behave similarly for expressions as for statements. In statements it only progressed if the previous condition is "true" (albeit for a shell interpretation of "true" -- ie zero exit number).

Likewise for `||`

The problem with expressions in Murex currently, is that they evaluate functions ahead of time. But thats actually the wrong behaviour. eg in C, Go, Java, and so on, in the following expression, `bar()` wouldn't be run if `foo()` was true: `baz = foo() || bar()`. And that's the same logic that Murex should follow too.

If that logic follows, then `&&` and `||` effectively behaves the same in all 3 examples below:
```
foo = ( fn() && fn() )
foo = ($variable && $variable)
command && command
```

**Comment by orefalo** [comment]
Wait now I am confused.

`conditional evaluation` and `binary evaluation` are two different things, aren't they?

Ah, think I am starting the see what you mean...

for variables: 0 && 1 && 0
here the evaluation will stop on the "1" and return false

for functions : 0 && 0 && 1
here each function will run and return an exitnum, 

is 0 -> true
anything else -> false

so yes, you are right, it's the same logic.

**Comment by lmorg** [comment]
The one question that needs to be decided though, is how STDOUT is handled. take the following code:
```
$var = (out(true) && out(true))
```
should `$var` equal: `"true\ntrue\n"` (the STDOUT of both functions) or `true`, the boolean result of the operations?

I'm on the fence about this one. On the one hand, holding the boolean is more natural for an expression. But on the other hand, holding the STDOUT is more consistent with shell `&&` usage.

I'm inclined to go with the expression/boolean approach and have STDOUT discarded.

**Comment by orefalo** [comment]
> should $var equal: "true\ntrue\n" (the STDOUT of both functions) or true, the boolean result of the operations?

IMHO `true`  - the boolean result of the operations

**Comment by lmorg** [comment]
agreed.

Pushed a working prototype to `develop`

Current implementation doesn't suppress errors. eg
<img width="295" alt="image" src="https://github.com/lmorg/murex/assets/12153701/6020d577-b455-4309-a808-c40ce68f482e">

I think I'm going to leave it like that for v5.0. You can always `<!null>` the commands if you want the errors silenced.
