### ISSUE TITLE
How to redirect <stderr> to /dev/null?

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#709]
sorry but it's far from trivial...

in other shells I would do the following to ignore error messages

`mycommand 2>/dev/null`

**Comment by lmorg** [comment]
I thought this was in the Rosetta Stone but looks like I omitted it. Sorry about that. 

It’s
`mycommand <!null> parameters…`

**Comment by lmorg** [comment]
The ! Signals stderr. Without ! Would redirect STDOUT

**Comment by orefalo** [comment]
thank you, will add to Rosetta

**Comment by orefalo** [comment]
it doesn't work

```
➜  git rev-parse <!null> -q --git-dir --is-bare-repository
fatal: not a git repository (or any of the parent directories): .git
Error in `git` (0,1): exit status 128
```


```
➜  fish
Now using Node v18.16.0 (npm 9.5.1) ~/.local/share/nvm/v18.16.0/bin/node
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

~ via  v18.16.0
➜  git rev-parse  -q --git-dir --is-bare-repository 2>/dev/null

~ via  v18.16.0
```

**Comment by lmorg** [comment]
It needs to be after the command otherwise it gets parsed as a parameter:
```
git <!null> rev-parse -q --git-dir --is-bare-repository
```

**Comment by orefalo** [comment]
i see.. I will document all of this.
coming up with a list of things to do
