### ISSUE TITLE
Autocomplete to suggest values after flags have been added

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#762]
**Describe the query:**
In the simplest terms, I would like to make an autocompletion for some command `abc`. The autocompletion would suggest `xyz` as a completion for `abc`. `abc` also has a flag, `-foo`, for which the value `bar` would be suggested. If the user typed in `abc -foo bar `, and then hit Tab, I would like the autocompletion to suggest `xyz`.

My initial attempt looked like this:
```
3  autocomplete set abc { [{                                                                                                                                                              
    4      "Dynamic": ( { -> %[ "xyz" ] } ),                                                                                                                                                  
    5      "Flags": [ "-foo" ],                                                                                                                                                               
    6      "FlagValues": {                                                                                                                                                                    
    7          "-foo": [{                                                                                                                                                                     
    8              "Flags": [ "bar" ]                                                                                                                                                         
    9          }]                                                                                                                                                                             
   10      }                                                                                                                                                                                  
   11  }] }  
```
This causes both `xyz` and `-foo` to be suggested for `abc`, but after I add `-foo bar` either via using the autocompletion Tab+Enter, or typing it manually, when I hit Tab again, `xyz` is no longer suggested.

I've played around with toggling `AllowAny`, `AllowMultiple`, and `Optional`, as well as changing the nested `-foo` FlagValue to have a `Dynamic` code block suggesting `bar` rather than using the `Flags` array, but haven't found a way to produce the behaviour I'm looking for. Is adding autocompletions after flags are provided supported?

**Expected behaviour:**
That hitting tab after `abc -foo bar ` suggest `xyz`.

**Additional context:**
N/A

**Documentation:**
Please rate your success with referring to the docs @ https://murex.rocks
- [ ] I haven't read the docs / the solution should be more discoverable
- [x] I have read the docs but the content wasn't clear
- [ ] I have read the docs but this query was missing
- [ ] I have read the docs and this query was answered but I'm still having problems

[add any additional detail, this will help us to write better docs]

**Comment by lmorg** [comment]
What's happening with your code:
```
autocomplete set abc { [{
    "Dynamic": ( { -> %[ "xyz" ] } ),
    "Flags": [ "-foo" ],
    "FlagValues": {
        "-foo": [{
            "Flags": [ "bar" ]
        }]
    }
}] }
```
...is that `xyz` and `-foo` are both flags expected to be followed after the command.

The following code works as requested:
```
autocomplete set abc { [
    {
        "Flags": [ "-foo" ],
        "FlagValues": {
            "-foo": [{
                "Flags": [ "bar" ]
            }]
        },
        "optional": true
    },
    {
        "Dynamic": ( { -> %[ "xyz" ] } )
    }
] }
```

Where this differs is you're saying the first group is optional and `-foo` expects the value `bar`. The second group isn't optional and that returns the `xyz` value from your dynamic block.

**Comment by tiymat** [comment]
Thanks, that approach is working!

I've written a few autocompletions now and I thought I'd read the `autocomplete` builtin's documentation relatively thoroughly, but the concept of groups didn't really click for me until just now.

**Comment by lmorg** [comment]
Yeah, it's really explained in the docs. The basic idea is the groups are to define position dependant parameters. While `FlagValues` define flag dependant parameters.

In your case you needed a mixture of two: flag dependant (for `-foo`) but also position dependant (`xyz` must follow any optional flags).

The gotcha with this is if `xyz` can come before or after `-foo`.
