### ISSUE TITLE
Website: Opening "config" builtins page from left menu breaks site

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#780]
**Describe the bug:**
1. Open the website page for any builtin other than `config`. e.g. https://murex.rocks/commands/a.html
2. Click the `config` entry in the `Builtins` list on the left side of the screen.
3. Observe that the content for the page doesn't load, and the content of any other pages accessed via the left menu (not just builtins) also fails to load for the duration of the session.

**Expected behaviour:**
The `config` entry should display as expected when navigated to via the `Builtins` menu on the left

**Platform (please complete the following information):**
 - Ubuntu 23.04
 - Observed in LibreWolf 121.0-1, successfully reproduced in Google Chrome 120.0.6099.199

**Additional context**
After clicking `config` for the first time, the following error appears in the console.
`Uncaught DOMException: String contains an invalid character`

**Comment by lmorg** [comment]
Nice find! The weird thing about this is a refresh (eg `F5`) on the broken page then makes it load correctly. Anyhow, fixed this and pushed to `develop` (https://dev.murex.rocks) This will be pushed live along with your other bug report in a day or two.
