### ISSUE TITLE
"Nullness" of a JSON null is lost while iterating using formap

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#781]
**Describe the bug:**
When iterating over a JSON object using `formap`, `is-null` will always report the value as being non-null.

**Expected behaviour:**
`is-null` should behave the same whether or not it's invoked on the value of an object in a `formap` loop.

**Screenshots:**
```
~ » %{ "foo": null } -> set x
~ » if { is-null $x['foo'] } then { out "foo is null" } else { out "foo is NOT null" }
foo is null
~ » $x -> formap k v { if { is-null v } then { out "$k is null" } else { out "$k is NOT null" } }
foo is NOT null
```

**Platform (please complete the following information):**
 - OS, output from `uname -a` if supported: Ubuntu 23.04
 - Terminal Emulator: GNOME Terminal
 - Murex version, output from `version --no-app-name`: 5.3.6000

**Additional context:**
Can be worked around by disregarding the variable `formap` uses for the value like so
```
~ » $x -> formap k v { if { is-null $x[$k] } then { out "$k is null" } else { out "$k is NOT null" } }
foo is null
```
but I'm not sure if it's safe to access the value in this way while iterating over the object?

**Comment by lmorg** [comment]
Looks like you've uncovered not one, but two bugs in the parser.

## `null` bareword parsed as string:

```
» %{ "foo": null }
{
    "foo": "null"
}
```

## variables are tokenised for `is-null` parameters

```
» $foo = "bar"
» is-null foo
foo: defined and not null
» is-null $foo
bar: undefined or null
```

---

Both of these are trivially fixable so I'll get an update pushed to `develop` shortly

**Comment by lmorg** [comment]
@tiymat pushed a fix to `develop`. I'll probably put this live in the next day or two because it's a low impact change.

**Comment by tiymat** [comment]
In testing the `develop` version (5.3.7000) I noticed a potentially-related issue.

In JSON objects constructed with `%{}` syntax, `is-null` seems to interpret empty strings as nulls, contradicting the [documentation](https://murex.rocks/commands/is-null.html) which says "Zero length strings [...] are all not null."

```
tmp » cat test.mx
#!/usr/bin/murex

%{ "foo": "" } -> formap key value {
	if { is-null value } then {
		out "value is null"
	} else {
		out "value is NOT null"
	}
}
tmp » ./test.mx
value is null

```

**Comment by lmorg** [comment]
Good spot.

The parser for object creator was a little slapdash. I'm pretty sure I wrote that code wrapped under a blanket while fighting off covid. Which also explains why the tests aren't thorough enough.

I'm going to merge the changes I have currently and will rewrite the object creator parser for a new release.
