### ISSUE TITLE
Murex bug: database is locked (5) (SQLITE_BUSY): '/home/me/.murex_modules/cache.db'

### ISSUE THREAD

**Issue by notjames** [lmorg/murex#788]
**Describe the bug:**
I'm just starting to check out murex. I've added murex to /etc/shells and I've logged in a new shell. 
Under one login, I installed the following according to https://github.com/orefalo/murex-module-starship:
```
$ murex-package install https://github.com/orefalo/murex-module-starship.git
$ murex-package update
logged out
```

Upon next login, the following occurs:
```
You have no mail.
Last login: Thu Jan 25 14:42:41 2024 from 192.168.0.53
Loading profile `.murex_preload`
Loading module `murex-module-starship/starship`
Loading profile `.murex_profile`
Error querying cache in hint_summary: database is locked (5) (SQLITE_BUSY): '/home/me/.murex_modules/cache.db'
This is a murex bug. Please raise an issue at https://github.com/lmorg/murex/issues
!!! Disabling persistent cache !!!
[WARN] - (starship::modules::custom): Executing custom command "git getreponame" timed out.
[mWARN] - (starship::modules::custom): You can set command_timeout in your config to a higher value or set ignore_timeout to true for this module to allow longer-running commands to keep executing.
```

**Expected behaviour:**
I expect no errors to occur and I expect no messages requesting my create an issue :)

**Screenshots:**
N/A

**Platform (please complete the following information):**
 - OS, output from `uname -a` if supported: Ubuntu 22.04 LTS
 - Terminal Emulator: [e.g. iTerm2, Konsole] : tilix, iterm2 (via ssh)
 - Murex version, output from `version --no-app-name`: [e.g. 2.12.1200]: 5.3.7000

**Additional context**
Do note that I do use starship prompt version 1.16.0

**Comment by lmorg** [comment]
How was murex built? Was it compiled from source or the binary downloaded from (eg) Github?

The actual error can be ignored, it just means the new invocation isn't going to use the existing cache. But the cache is a recent addition and there's plenty of controls in place to ensure that performance is still there even without cache. So this error is not actually impactful. To that end I'm going suppress that error in the next release.
