### ISSUE TITLE
Option to hide "Loading profile" messages on start

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#797]
**Describe the problem:**
It would be nice to be able to hide the `Loading profile`/`Loading module` messages that occur when the shell starts up. I don't think this would make debugging issues with a module or profile more difficult, as if I put a wrong/gibberish command in e.g. my `.murex_profile` file, the file and line number of the offending command will still be visible in the stderr.

**Possible ways to implement:**
Not sure, I actually looked into writing a pull request implementing this as config option in the `shell` app, with the default set to the existing behaviour of showing the messages.
However, I ran into the issue that the messages are printed before the file is parsed. Setting the config option in `.murex_preload` would hide the later message about loading `.murex_profile`, but not the one about loading `.murex_preload` itself, etc.

It could well be that in practice this is unworkable or not worth the time, but if not I think it would be a nice feature to have.

**Comment by lmorg** [comment]
Yeah, this couldn't be a setting in `.murex_preload` unfortunately for exactly the reason you outlined. But it could be an environmental variable and/or command line flag that is passed to murex upon start up. eg `murex --quiet`
