### ISSUE TITLE
Formatting a JSON Object as CSV no longer works

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#801]
**Describe the bug:**
The formatting of a JSON list to a CSV described [here](https://github.com/lmorg/murex/issues/689#issuecomment-1694062313) no longer works; `format` returns exitnum 0 but doesn't emit anything to stdout.

**Expected behaviour:**
The format operation should emit CSV-formatted data as it used to.

**Screenshots:**
![image](https://github.com/lmorg/murex/assets/138939221/5f744e81-781e-453c-9a3c-f5f09c472faf)

**Platform (please complete the following information):**
 - OS, output from `uname -a` if supported: 6.9.1-arch1-1
 - Terminal Emulator: wezterm 20240203-110809-5046fc22
 - Murex version, output from `version --no-app-name`: 6.0.1000

**Additional context**
I tried explicitly casting the results of `open` to json before attempting to format it, but it didn't make a difference.

**Comment by lmorg** [comment]
Looks like it's failing to marshal CSV in a number of scenarios. eg
```
ps aux -> format csv             # works
ps aux -> head -n5 -> format csv # empty
```
That's very weird. I'll take a look tonight

**Comment by lmorg** [comment]
Turns out all it was, was a write buffer flush happening before the final read. Silly mistake. Sorry about that

**Comment by tiymat** [comment]
Thanks for the fix!

**Comment by lmorg** [comment]
np. Sorry for the regression. I've put some testing around it to hopefully catch any future regressions there before they merge into `master`
