### ISSUE TITLE
Comparing two arrays or two maps with `==` causes a panic

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#831]
**Describe the bug:**
Executing an expression with using `==` to compare two arrays or two maps causes a panic (comparing one map and one array does not panic.)

```
%{"foo": "bar"} == %[1] # false
%{"foo": "bar"} == %{"bar": "baz"} # panic
%[1] == %[1] # panic
```

**Expected behaviour:**
An error should be printed without panicking. (Unless `==` is a reasonable thing to do with two arrays or maps? I couldn't find documentation for `==` under the Operators and Tokens section on the site.)

**Screenshots:**
N/A

**Platform (please complete the following information):**
 - OS, output from `uname -a` if supported: 6.9.8-arch1-1
 - Terminal Emulator: kitty 0.35.2
 - Murex version, output from `version --no-app-name`: 6.1.8300

**Additional context**
N/A

**Comment by lmorg** [comment]
That is a weird one. Works when the array is either side, but not when it is both sides.

**Comment by lmorg** [comment]
Found the issue. Pushed the fix (plus additional tests) to `develop`
