### ISSUE TITLE
Should `~` error if username not found?

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#840]
**Describe the problem:**
The unhappy path for `~` is to produce root path:

```
» ~foobar
/
```

This could lead to errors creeping in silently.

**Possible ways to implement:**
If username does not exist, then produce an error like if a `$variable` doesn't exist.

**Comment by laurence-nearform** [comment]
Indeed. The original behaviour was written to mimic Bash. But things have moved on significantly since that piece of the code was last touched.
