### ISSUE TITLE
Empty string check broken for some variables

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#845]
**Describe the bug:**
When you set a variable to the output of a command that outputs the empty string, later checks of the variable's value won't report it as being equal to the empty string.

**Expected behaviour:**
When the output of a command that emits the empty string is saved to some variable `var`, `$var == ""` should be `true`.

**Screenshots:**
![image](https://github.com/user-attachments/assets/083a2fce-2f99-4cbf-a95b-bca01cd7f8e8)

**Platform (please complete the following information):**
 - OS, output from `uname -a` if supported: 6.9.10-arch1-1
 - Terminal Emulator: kitty 0.35.2
 - Murex version, output from `version --no-app-name`: 6.2.3000

**Additional context**
Ran into this because it breaks the direnv hook.

I believe the change that causes this was introduced in the most recent release.

Seems to be related to the fact that the data type of the variable is set to `*`. If I change the command in the screenshot from `printf ""` to `out ""`, it will behave as expected, presumably because `out` passes along the fact that the variable is a `str` through the pipe to `set`.

**Comment by lmorg** [comment]
Pushed a fix to `master`. New binaries are being built....
